POST http://localhost:8765/hr-oauth/oauth/token
Authorization: Basic myappname123 secret123
Content-Type: application/x-www-form-urlencoded

username = renan@gmail.com &
password = senha123 &
grant_type = password


###
GET http://localhost:8765/hr-worker/workers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDgzOTMzMDQsInVzZXJfbmFtZSI6InJlbmFuQGdtYWlsLmNvbSIsImF1dGhvcml0aWVzIjpbIlJPTEVfT1BFUkFUT1IiXSwianRpIjoiZTIzZjVmNDItMDFmOC00OWU1LWE4NDgtOGQ3NjQ1OTNlMWE3IiwiY2xpZW50X2lkIjoibXlhcHBuYW1lMTIzIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl19.k-l6r94DfAer7ggRmf3HjUjWQxz0sMtZr9nC7T3zlZM

###
GET http://localhost:8765/hr-payroll/payments/1/days/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDgzOTM4NTUsInVzZXJfbmFtZSI6ImxhcmFAZ21haWwuY29tIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiJdLCJqdGkiOiI1NTIyYmZhNi1mNmU0LTQxNjUtYTcwZC1jNDY4MDFjMDhjN2QiLCJjbGllbnRfaWQiOiJteWFwcG5hbWUxMjMiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXX0.w_OyRlbHChyeyJgksitgShkpNFJ2DlmSiKSpC7w58Mg

