POST http://localhost:8765/hr-oauth/oauth/token
Authorization: Basic myappname123 myappsecret123
Content-Type: application/x-www-form-urlencoded

username = renan@gmail.com &
password = senha123 &
grant_type = password


###
GET http://localhost:8765/hr-worker/workers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDg2NTU2OTAsInVzZXJfbmFtZSI6InJlbmFuQGdtYWlsLmNvbSIsImF1dGhvcml0aWVzIjpbIlJPTEVfT1BFUkFUT1IiXSwianRpIjoiY2I5NzlhNjEtZGUwZi00NGI3LTg5ZTEtMzk4MDFlMmNjMTEzIiwiY2xpZW50X2lkIjoibXlhcHBuYW1lMTIzIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl19.jWFL4vVvNVMs7G6zI8yC9Mj67LE3ZxxV0gGbMCbU3qI

###
GET http://localhost:8765/hr-payroll/payments/1/days/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDgzOTM4NTUsInVzZXJfbmFtZSI6ImxhcmFAZ21haWwuY29tIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiJdLCJqdGkiOiI1NTIyYmZhNi1mNmU0LTQxNjUtYTcwZC1jNDY4MDFjMDhjN2QiLCJjbGllbnRfaWQiOiJteWFwcG5hbWUxMjMiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXX0.w_OyRlbHChyeyJgksitgShkpNFJ2DlmSiKSpC7w58Mg

